// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv4auuv0Wvkr_-GyKvLfTruarI59AxVc8',
    appId: '1:580147198974:web:c5b8b3f6c13085fe2edeaf',
    messagingSenderId: '580147198974',
    projectId: 'swasthai-8e8b4',
    authDomain: 'swasthai-8e8b4.firebaseapp.com',
    storageBucket: 'swasthai-8e8b4.firebasestorage.app',
    measurementId: 'G-CHEBDS2R7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFGHbsh1E8994PgIWhr0vXol02X-tBOgI',
    appId: '1:580147198974:android:0058294b85ea470d2edeaf',
    messagingSenderId: '580147198974',
    projectId: 'swasthai-8e8b4',
    storageBucket: 'swasthai-8e8b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd7ojpzqhwf-44vQVmCagv8BC1ds1CFNY',
    appId: '1:580147198974:ios:9f160ee7fa4037e22edeaf',
    messagingSenderId: '580147198974',
    projectId: 'swasthai-8e8b4',
    storageBucket: 'swasthai-8e8b4.firebasestorage.app',
    iosBundleId: 'com.example.hackOdisha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd7ojpzqhwf-44vQVmCagv8BC1ds1CFNY',
    appId: '1:580147198974:ios:9f160ee7fa4037e22edeaf',
    messagingSenderId: '580147198974',
    projectId: 'swasthai-8e8b4',
    storageBucket: 'swasthai-8e8b4.firebasestorage.app',
    iosBundleId: 'com.example.hackOdisha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv4auuv0Wvkr_-GyKvLfTruarI59AxVc8',
    appId: '1:580147198974:web:298295742e6057c42edeaf',
    messagingSenderId: '580147198974',
    projectId: 'swasthai-8e8b4',
    authDomain: 'swasthai-8e8b4.firebaseapp.com',
    storageBucket: 'swasthai-8e8b4.firebasestorage.app',
    measurementId: 'G-2Y8EX6HP3J',
  );
}
